/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gabriel.randungeon.interfaceGrafica;

import gabriel.randungeon.Consumivel;
import gabriel.randungeon.Personagem;
import javax.swing.DefaultListModel;

/**
 *
 * @author Gabriel
 */
public class PainelGerenciamentoCinto extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    
    Personagem personagem;
    
    public PainelGerenciamentoCinto(Personagem personagem) {
        initComponents();
        this.personagem = personagem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaMochila = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaCinto = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addCinto = new javax.swing.JButton();
        removeCinto = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 400));

        listaMochila.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listaMochila.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaMochila.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jScrollPane1.setViewportView(listaMochila);

        listaCinto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listaCinto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaCinto.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jScrollPane2.setViewportView(listaCinto);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel1.setText("Itens na Mochila:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setText("Itens no Cinto:");

        addCinto.setText("Adicionar ao Cinto");
        addCinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCintoActionPerformed(evt);
            }
        });

        removeCinto.setText("Remover do Cinto");

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(addCinto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeCinto)
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCinto)
                    .addComponent(removeCinto))
                .addGap(18, 18, 18)
                .addComponent(voltar)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void addCintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCintoActionPerformed
        
        DefaultListModel<String> modeloMochila = (DefaultListModel) listaMochila.getModel();
        DefaultListModel<String> modeloCinto = (DefaultListModel) listaCinto.getModel();
        modeloCinto.addElement(listaMochila.getSelectedValue());
        listaCinto.setModel(modeloCinto);
        GUI.itensCinto.add(Consumivel.getConsumivelPorNome(listaMochila.getSelectedValue()));
        Consumivel.getConsumivelPorNome(listaMochila.getSelectedValue()).equipa();
        GUI.itensMochila.remove(Consumivel.getConsumivelPorNome(listaMochila.getSelectedValue()));
        
        modeloMochila.removeElement(listaMochila.getSelectedValue());
        listaMochila.setModel(modeloMochila);
    }//GEN-LAST:event_addCintoActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        GUI.telaGerenciadorCinto.setVisible(false);
        GUI.entreSalas(personagem);
    }//GEN-LAST:event_voltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCinto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JList<String> listaCinto;
    protected javax.swing.JList<String> listaMochila;
    private javax.swing.JButton removeCinto;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
