
package gabriel.randungeon.interfaceGrafica;

import gabriel.randungeon.Consumivel;
import gabriel.randungeon.Equipavel;
import gabriel.randungeon.Item;
import gabriel.randungeon.Monstro;
import gabriel.randungeon.Personagem;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class PainelSalaMonstro extends javax.swing.JPanel {

    Monstro monstro;
    Personagem personagem;
    
    public PainelSalaMonstro(Monstro monstro, Personagem personagem) {
        initComponents();
        this.monstro = monstro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeMonstro = new javax.swing.JLabel();
        poderMonstro = new javax.swing.JLabel();
        poderPlayer = new javax.swing.JLabel();
        botaoLutar = new javax.swing.JButton();
        botaoCinto = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 400));

        nomeMonstro.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        nomeMonstro.setText("Um " + this.monstro.getNome() + " apareceu!");

        poderMonstro.setText("O poder do monstro é " + this.monstro.getPoder());

        poderPlayer.setText("O poder do jogador é " + this.personagem.getPoderCombate());

        botaoLutar.setText("Lutar");
        botaoLutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLutarActionPerformed(evt);
            }
        });

        botaoCinto.setText("Abrir cinto");
        botaoCinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCintoActionPerformed(evt);
            }
        });

        jButton3.setText("Fugir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeMonstro)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poderPlayer)
                            .addComponent(poderMonstro)
                            .addComponent(botaoLutar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoCinto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(30, 30, 30)))
                .addGap(0, 132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(nomeMonstro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(poderMonstro)
                .addGap(18, 18, 18)
                .addComponent(poderPlayer)
                .addGap(18, 18, 18)
                .addComponent(botaoLutar)
                .addGap(18, 18, 18)
                .addComponent(botaoCinto)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLutarActionPerformed
        if(this.personagem.getPoderCombate() > this.monstro.getPoder()){
            this.personagem.addNivel();
            this.personagem.addDinheiro(this.monstro.calculaRecompensa());
            personagem.resetaAuxiliarPoderCombate();
            JOptionPane.showMessageDialog(this, "Parabéns! Você derrotou o monstro! Sua recompensa foi de: "
                    + this.monstro.calculaRecompensa() + " moedas de ouro!");
            int x = (int)(Math.random()*100);
            if(x <= 25){
                Item item = Item.sorteiaItem();
                this.personagem.addMochila(item);
                JOptionPane.showMessageDialog(this, "Um tesouro adicional foi encontrado! Você obteve o item " + item.getNome());
            }
        }else{
            personagem.morte();
            JOptionPane.showMessageDialog(GUI.menu, "Você morreu! Tente novamente!");
            GUI.usuarioAtual.removePersonagem(personagem);
            GUI.telaGerenciamentoPersonagens();
        }
    }//GEN-LAST:event_botaoLutarActionPerformed

    private void botaoCintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCintoActionPerformed
        
    }//GEN-LAST:event_botaoCintoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCinto;
    private javax.swing.JButton botaoLutar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel nomeMonstro;
    private javax.swing.JLabel poderMonstro;
    private javax.swing.JLabel poderPlayer;
    // End of variables declaration//GEN-END:variables
}
